### ISSUE TITLE
Issues installing package (mac)

### ISSUE THREAD

**Issue by cgotz17** [juancarlospaco/faster-than-requests#115]
So I'm having an issue installing this package. I think because the zip file is labeled differently than the version number on PyPI, pip is giving me some grief

So if I just do...

> `$ python3 -m pip install faster-than-requests`

... it downloads `faster_than_requests-3572925.zip` and gives me this error:

> `ERROR: Requested faster-than-requests from https://files.pythonhosted.org/packages/8f/f0/11be00462bf64c327f73fb2696fc8f0c9e0cd495369569f0f0d6cded5c55/faster_than_requests-3572925.zip#sha256=24f9b9d9fb81dbfac8af4ff3672bed0d99b566e7d64f4efeb8bf96932a4700d4 has different version in metadata: '20.10.19'`

then if I try to specify the version number...

> `$ python3 -m pip install faster-than-requests==20.11.04`

... I get this error:

> ERROR: Could not find a version that satisfies the requirement faster-than-requests==20.11.04
> ERROR: No matching distribution found for faster-than-requests==20.11.04

Is there something I'm doing wrong? Or maybe is there just some way for me to get override the conflict between the file name and the version number embedded in metadata?

**Comment by bsteenwi** [comment]
Not sure if its related to this; but pip install works on linux if you add an additional flag:
`python3.8 -m pip install faster-than-requests --no-binary :all: --use-deprecated=legacy-resolver`

As noted in the pip notes:
`you need a workaround while the root cause of this problem is being fixed, so you can choose the old resolver behavior using the flag --use-deprecated=legacy-resolver. This will work until we release pip 21.0`
