### ISSUE TITLE
async support

### ISSUE THREAD

**Issue by ekremus** [juancarlospaco/faster-than-requests#167]
Hello,
Will there be async library support in the future?

Additionay,
when using pip to install on pycharm, there is problem occurs. (Im using, latest pip and latest pycharm)

`WARNING: Discarding https://files.pythonhosted.org/packages/f0/9b/f392487c0ddb086aad681a781fbb1da4fcd2761920d20cfae18ecb724e67/faster_than_requests-21.03.03.zip#sha256=3cc247556e10c64d8897933304670c873236026b
4ef9f219215b124e990c2dac (from https://pypi.org/simple/faster-than-requests/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement faster_than_requests (from versions: 21.3.3)
ERROR: No matching distribution found for faster_than_requests
`

**Comment by juancarlospaco** [comment]
It is async internally already, for example the Web Socket is async.

Public API can not have async, because Python does not support Closures,
real Closures not workarounds that resemble a Closure, not my bug.

Terminals inside IDE sometimes are buggy, 
try on the system terminal window (Bash or PowerShell).

The error is a PIP/Pypi error, that error does not come from our code.
Git clone and compile if PIP keeps giving you errors.
