### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by Hellowlol** [juancarlospaco/faster-than-requests#4]
The actions seems to be in plual.

gets instead of get etc. Is this intended? I was just wondering since the example says ``import faster_than_requests as requests``` so I expected that the compatibility regarding the "most common" methods.

**Comment by juancarlospaco** [comment]
But urllib.requests dont have such actions, is not designed as drop-in replacement to any other lib.
I will not add mimicking of other libs, because no other lib has same actions, having said that, Pull Requests are welcome to add such imitation if they are like alias to the existing functionalities.
As the Readme says it also has other sister libs also similar but for CSV and walk.
:slightly_smiling_face:

**Comment by Hellowlol** [comment]
Oh, i just assumed this was for http://docs.python-requests.org/en/master/ thanks for the clear up.

**Comment by juancarlospaco** [comment]
This project is not the same as the linked project.
You can easy alias stuff when importing on Python `from foo import bar as baz` then use `baz()`.
No other libs provide the same features we have (NDJSON, Pretty-Printed JSON, Download with randomized delays, etc etc) at least at the time of creating it.
Pull Requests are welcome.
:slightly_smiling_face:

**Comment by Hellowlol** [comment]
Any way to add alias to gets to get while keeping things dry?  If this was python i would have added a decorator that does this for me. (first time I looking at nim :) )

**Comment by juancarlospaco** [comment]
Let me give a little history of the project...

The project started as a [coding live stream on my Twitch](https://www.twitch.tv/juancarlospaco) on the [Programming category](https://www.twitch.tv/directory/game/Science%20%26%20Technology), 
people choosed the project name, output formats like JSON, NDJSON, a little of the API, etc.

Some people said that want to use both Requests and this project on the same file,
Requests already has a `get()` if we also had a `get()` it will be name collision, 
some people just import it like `from requests import get` it seems (?), or maybe PyCurl (?),
then we used `gets()`, then you can do `get()` and `gets()` on the same file.

If you want to change or expand the API, is possible to design the API on here, 
I just changed the Issue title to reflect the ideas on this issue,
but think that other libs needs other parameters, that we dont need, what to do with those?,
how to keep our `get()` and Requests `get()` not crashing on each others?,
functions with many arguments are slow on Python, because the body of the function is full of `if..else`,
this lib is friendly to people doing API & Data Science that tend to use formats like JSON & CSV.

So considering input arguments and output returns always will be different, 
now feel free to comment how you think the API should be :grey_question: 

Dont worry I come from Cython too.
Most of heavy work is done by [Nimpy](https://github.com/yglukhov/nimpy#implementing-python-module-in-nim).
But nowadays Nim has cool [Documentation](https://nim-lang.org/learn.html) and [standard lib Documentation](https://nim-lang.org/docs/lib.html).
:cat:

**Comment by juancarlospaco** [comment]
Fixed on master.

**Comment by nwalsh1995** [comment]
My $0.02:

> Some people said that want to use both Requests and this project on the same file,
Requests already has a get() if we also had a get() it will be name collision

This is exactly what `from _ import _ as _` is for. You already mentioned that you would expect people to do `from _ import gets as get` for a drop-in replacement of requests, but why not keep it compatible and then if someone wants to use both they do the import?

To me, `gets` makes no sense, it could mean "perform multiple GETs" or it could be "perform a GET and return value as **s**tring". Is there any reason for this naming besides not stomping on requests API?

**Comment by juancarlospaco** [comment]
It has features beyond the ones provided by Requests and urllib.requests so the same API is not very realistic,
exactly the same way Requests API is not the same as urllib.requests.

Its not designed as a drop-in replacement clone of any other lib.

But we keep improving on the usability of the API, 
the first version was to add the basic features and extra features requested by people, 
maybe on the next version it can improve the API, on naming and stuff like that.
:slightly_smiling_face:
