### ISSUE TITLE
Benchmarking slower than vanilla requests

### ISSUE THREAD

**Issue by aJetHorn** [juancarlospaco/faster-than-requests#82]
**Describe the bug**
Benchmarking a single HTTP get using FTR versus vanilla requests. FTR seems much slower. Potentially, this is a bug. Perhaps I am misunderstanding the purpose of this library.

```
FTR
real	0m2.780s
user	0m0.072s
sys	0m0.073s

Vanilla
real	0m0.808s
user	0m0.156s
sys	0m0.100s
```

**Expected behavior**
I would expect all queries to be faster than vanilla requests

**Desktop (please complete the following information):**
 - OS: iOS
 - Python Version 3.6.6
 - Faster Than Requests Version: Latest
 - Requests version: 2.20.0

**Additional context**
I used the hacky iOS install steps seeing as iOS pip install still doesn't work

**Comment by juancarlospaco** [comment]
This is invalid without full Repro code.
That version of Python is old.
:shrug:

**Comment by aJetHorn** [comment]
```
$ time python a4.py

real	0m4.657s
user	0m0.092s
sys	0m0.099s
$ time python b4.py

real	0m1.531s
user	0m0.181s
sys	0m0.117s

$ cat a4.py b4.py
import faster_than_requests as requests
archive_address = "https://github.com/juancarlospaco/faster-than-requests/issues/82"
r = requests.get(archive_address)

import requests
archive_address = "https://github.com/juancarlospaco/faster-than-requests/issues/82"
r = requests.get(archive_address)
```

**Comment by juancarlospaco** [comment]
Code is wrong, use `faster_than_requests.get2str()`. 
Thats not vanilla, thats third party lib.

**Comment by aJetHorn** [comment]
So, to be clear, _faster_than_requests_ is not actually faster than requests for the HTTP GET base case? The way your README is worded and the examples you provided in [this post](https://dev.to/juancarlospaco/faster-than-requests-1a25) are very confusing. If the library is slower for the main case that any curious user would first attempt, you should provide an explanation for this rather than telling people their code is wrong.

'Vanilla requests' is recognizable as the requests library you're referencing being faster than, right? I don't see why it's necessary to point out that it isn't standard library.

**Comment by juancarlospaco** [comment]
Theres no main function, nor base, or whatever name, use them freely.

Not everyone understand the difference nowadays about vanilla, stdlib, etc
that some tools depend on Requests some people dont know that.

**Comment by juancarlospaco** [comment]
So, trying to understand and reach some kind of conclusion:

- This is not drop-in replacement of any pre-existent software.
- Functions are free floating functions.
- Not everyone understand the difference between vanilla and stdlib.
- The function naming is different, the API is different because the libs are different.
- We offer a simpler and faster alternative to other libs `get()`.
- Maybe in the future `get2str()` can be renamed to `get()` to avoid confusions.
- Performance may change depending how you compiled it, some compile options are designed as slow as possible for debug.
- Maybe you are right and you misunderstand the library as you said, feel free to use whatever you like best.
- We are working on new features all the time.
